### ISSUE TITLE
Chrome password stealer chrome update

### ISSUE THREAD

**Issue by knightscode94** [Guereak/USBDuckyScripts#1]
tested on a dummy PC asks for windows security password then fails :(

**Comment by MaximeLglr** [comment]
Looked like it worked on every machine I've tested it on. Will investigate it further though, thanks for the feedback !

**Comment by knightscode94** [comment]
Wow that was a quick response thank you I can send screenshots if you need anymore information! On 3 Sep 2021 20:10, Guereak ***@***.***> wrote:
Looked like it worked on every machine I've tested it on. Will investigate it further though, thanks for the feedback !

**Comment by MaximeLglr** [comment]
I think I understand what is happening there. I tested this on my desktop PC which, being a desktop PC, has no password. Unfortunatly if it asks for the computer I don't think I can do something about that but I'll definetly try to see if there's a workaround.

**Comment by knightscode94** [comment]
Thank you! I will have a play too I just wanted to make you aware of it first as i is your codeOn 3 Sep 2021 22:20, Guereak ***@***.***> wrote:
I think I understand what is happening there. I tested this on my desktop PC which, being a desktop PC, has no password. Unfortunatly if it asks for the computer I don't think I can do something about that but I'll definetly try to see if there's a workaround.

**Comment by Pourino** [comment]
@Guereak Ey so testing Ur Script on a few systems gave me this error on all of the systems

Cannot convert argument "item", with value: "Documents/chromepasswords.csv", for "Add" to type
"System.Net.Mail.Attachment": "Cannot convert value "Documents/chromepasswords.csv" to type
"System.Net.Mail.Attachment". Error: "Could not find file 'C:\Users\(Username)\Documents\chromepasswords.csv'.""
At line:1 char:1
+ $E.Attachments.Add($F)
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

Any Help is appreciated

**Comment by MaximeLglr** [comment]
@Pourino because of a recent security update, it appears that the file cannot be created if the device you are trying to run this on a device with a password or any form of biometric authentication. (too good to be true otherwise) 
Therefore this script will now only work on devices that doesn't require a password to login. If the script isn't working either for you on those, you may want to try adding 2 more lines as explained in the README file.
